name: places_resnet152
print_freq: 100
workers: 48
log_dir: 'logs'

# dataset & model setting
dataset: 'places'
data_path: './data/Places365/'
num_classes: 365
imb_factor: null
backbone: 'resnet152'
resume: ''
head_class_idx:
  - 0
  - 131
med_class_idx:
  - 131
  - 288
tail_class_idx:
  - 288
  - 365


# Train
lr: 0.1
batch_size: 256
weight_decay: 5e-4
num_epochs: 90
momentum: 0.9

# scheduler - sch_mode can be cosine or multistep

sch_mode: cosine

